name: aml-pipeline
channels:
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.10.0
  - torchvision=0.11.1
  - pillow==9.0.1
  - tqdm==4.64.0
  - mlflow==1.26.0
  - yapf==0.31.0
  - pylint==2.12.2
  - mypy==0.910
