$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
experiment_name: aml-pipeline

compute: azureml:cluster-gpu

inputs:
  data_dir:
    path: azureml:data-fashion-mnist@latest
    type: uri_folder

jobs:
  train:
    type: command
    component: azureml:component_train@latest
    inputs:
      data_dir: ${{parent.inputs.data_dir}}
    outputs:
      model_dir:
        type: mlflow_model

  test:
    type: command
    component: azureml:component_test@latest
    inputs:
      model_dir: ${{parent.jobs.train.outputs.model_dir}}
      data_dir: ???

  # test_mlflow:
  #   type: command
  #   component: azureml:component_test_mlflow@latest
  #   inputs:
  #     model_dir: ${{parent.jobs.train.outputs.model_dir}}
  #     # Question: do I need to register the test data with Azure ML?
  #     test_data:
  #       path: azureml:data-fashion-mnist-test@latest
  #       type: uri_file